general {
	gaps_in = 8
	gaps_out = 12
}

decoration {
	rounding = 12
	blur {
		enabled = true
		size = 8
		passes = 3
		new_optimizations = true
		ignore_opacity = true
		xray = false
		noise = 0.02
	}

	shadow {
		enabled = true
		range = 30
		color = rgba(0,0,0,0.40)
	}
}
