# execute background processes at launch
# as hyprland doesn't start xdg autostart, fcitx5 must be launched here

# Environment variables safety measure for portals/tray/notifications
exec-once = dbus-update-activation-environment --systemd --all

# Start hyprland-session.target to manage Waybar and other session services
exec-once = systemctl --user start hyprland-session.target

exec-once = fcitx5 &
exec-once = hyprpaper &
# exec-once = hyprpanel 
exec-once = dunst &
# Waybar is now managed by systemd service (hyprland-session.target)
# exec-once = if [ ! $(pgrep waybar) ]; then waybar; fi
exec-once = reload-d &
exec-once = walker --gapplication-service &
exec-once = hypridle &

# execute apps at launch
exec-once = [workspace 1 silent] kitty
exec-once = [workspace 2 silent] zen-beta # firefox
exec-once = [workspace 3 silent] discord # legcord can't do ctl+T, vesktop don't even launch
exec-once = [workspace 4 silent] slack
# exec-once = [workspace 4 silent] discord # this doesn't launch discord at ws 4
# exec-once = [workspace 5 silent] kitty cmus 
# exec-once = [workspace 5 silent] kitty cava
exec-once = hyprctl dispatch workspace 1
