include ./current-theme.conf
include ./hardware-dep.conf
confirm_os_window_close 0
# font_family CodeNewRoman Nerd Font # not supported - normal font doesn't seem to load successfully
# font_family DejavuSansM Nerd Font
font_family MesloLGM Nerd Font
# font_family NotoSans Nerd Font

# BEGIN_KITTY_THEME
# Apprentice
# include current-theme.conf
# END_KITTY_THEME
