# you want to run `hyprland monitors all` to see the list
$mainMonitor = eDP-1
$mirrorMonitor = DP-1
$resolution = highrr # 1920x1080@60
$scale = 1.333333

# default to all monitors
monitor=,$resolution,0x0,$scale
# monitor-specific
# monitor=$mirrorMonitor,$resolution,0x0,1,mirror,$mainMonitor

# mouse sens is dependent on hardware
input {
	sensitivity = 0.3
	touchpad {
		disable_while_typing = true
		scroll_factor = 0.15
	}
}
