# you want to run `hyprland monitors all` to see the list
$mainMonitor = eDP-1
$mirrorMonitor = DP-1
$scale = 1.0
$resolution = highrr # 1920x1080@60

# all monitors
monitor=,$resolution,0x0,1.0
# mirror main -> sub
# monitor=$mainMonitor,$resolution,0x0,1
# monitor=$subMonitor,$resolution,0x0,1,mirror,$mainMonitor
# mirror sub -> main
# monitor=$subMonitor,$resolution,0x0,1
# monitor=$mainMonitor,$resolution,0x0,1,mirror,$subMonito

cursor {
	no_hardware_cursors = false # set it true if mouse cursor doesn't work correctly
}

# mouse sens is dependent on hardware
input {
	sensitivity = 0.3
	touchpad {
		disable_while_typing = true
		scroll_factor = 0.15
	}
	accel_profile = flat
}
