# change this to your monitor (run `hyprctl monitors list` to see all monitors)
$monitor = eDP-1

$path = /home/aster/decorations/wallpaper/storage/wallpaper.jpg

preload = $path

wallpaper = $monitor, $path

splash = false

# fully disable ipc
# ipc = off
