# execute background processes at launch
exec-once = fcitx5 # daemons
exec-once = waybar & hyprpaper # hypr daemons

# execute apps at launch
exec-once = [workspace 1 silent] kitty
exec-once = [workspace 2 silent] firefox
exec-once = [workspace 3 silent] slack
exec-once = [workspace 4 silent] 
exec-once = [workspace 5 silent] kitty cmus 
exec-once = [workspace 5 silent] kitty cava
exec-once = hyprctl dispatch workspace 1 &&
