# Window Rules
windowrulev2 = opacity 0.75, focus:0
windowrulev2 = opacity 0.85, class: ^(Alacritty)$, focus:1
# windowrulev2 = noblur, class: ^[^(kitty)]$
# windowrulev2 = opacity 0.75, class: ^(kitty)$
# windowrulev2 = opacity 0.6, class: ^(Alacritty)$
# windowrulev2 = opacity 0.55, focus:0
# windowrulev2 = noblur, class: ^[^(Alacritty)]$
windowrulev2 = opacity 1, fullscreen: 1,
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
