# execute background processes at launch
# as hyprland doesn't start xdg autostart, fcitx5 must be launched here
exec-once = fcitx5 &
exec-once = hyprpaper &
# exec-once = hyprpanel 
exec-once = dunst &
exec-once = if [ ! $(pgrep waybar) ]; then waybar; fi
exec-once = reload-d &
exec-once = walker --gapplication-service &
exec-once = hypridle &

# execute apps at launch
exec-once = [workspace 1 silent] kitty
exec-once = [workspace 2 silent] zen # firefox
exec-once = [workspace 3 silent] vesktop
exec-once = [workspace 4 silent] slack
# exec-once = [workspace 4 silent] discord # this doesn't launch discord at ws 4
# exec-once = [workspace 5 silent] kitty cmus 
# exec-once = [workspace 5 silent] kitty cava
exec-once = hyprctl dispatch workspace 1
