# execute background processes at launch
# as hyprland doesn't start xdg autostart
exec-once = fcitx5
exec-once = hyprpaper
exec-once = hyprpanel
exec-once = waybar
exec-once = reload-d
exec-once = walker --gapplication-service

# execute apps at launch
exec-once = [workspace 1 silent] kitty
exec-once = [workspace 2 silent] zen # firefox
exec-once = [workspace 3 silent] slack
exec-once = [workspace 4 silent] discord
# exec-once = [workspace 5 silent] kitty cmus 
# exec-once = [workspace 5 silent] kitty cava
exec-once = hyprctl dispatch workspace 1
