# execute background processes at launch
# exec-once = fcitx5
# Home Manager's eww module doesn't implement autostart yet
exec-once = hyprpanel
exec-once = walker --gapplication-service

# execute apps at launch
exec-once = [workspace 1 silent] alacritty
exec-once = [workspace 2 silent] zen # firefox
exec-once = [workspace 3 silent] slack
exec-once = [workspace 4 silent] discord
# exec-once = [workspace 5 silent] kitty cmus 
# exec-once = [workspace 5 silent] kitty cava
exec-once = hyprctl dispatch workspace 1
