# execute background processes at launch
exec-once = fcitx5
exec-once = waybar
exec-once = hyprpaper
exec-once = dunst

# execute apps at launch
exec-once = [workspace 1 silent] alacritty
exec-once = [workspace 2 silent] zen # firefox
exec-once = [workspace 3 silent] slack
exec-once = [workspace 4 silent] : # reserved
# exec-once = [workspace 5 silent] kitty cmus 
# exec-once = [workspace 5 silent] kitty cava
exec-once = hyprctl dispatch workspace 1
