# Window Rules
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# lower = higher priority
windowrulev2 = opacity 0.8, focus: 0
windowrulev2 = opacity 1, focus: 1
windowrulev2 = opacity 0.7, class: Alacritty, focus:0
windowrulev2 = opacity 0.7, class: kitty, focus:0
windowrulev2 = opacity 0.95, class: Alacritty, focus:1
windowrulev2 = opacity 1, fullscreen: 1,
