[ids]
*
# Exclude virtual keyboards used by voxtype so keyd doesn't remap their output
-4711:0815
-2333:6666

include layouts/workman
[global]
default_layout = workman

[main]
capslock = escape
escape = capslock
pageup = setlayout(main)
pagedown = setlayout(workman)
