[general]
import = [

  # Dark Theme
  # default also looks good
  # "~/.config/alacritty/themes/themes/catppuccin_frappe.toml",
  # "~/.config/alacritty/themes/themes/catppuccin_mocha.toml",
  #? "~/.config/alacritty/themes/themes/mariana.toml",
  # "~/.config/alacritty/themes/themes/material_theme.toml",
  # "~/.config/alacritty/themes/themes/nightfly.toml",
  # "~/.config/alacritty/themes/themes/nightfox.toml",
  # "~/.config/alacritty/themes/themes/one_dark.toml",
  # "~/.config/alacritty/themes/themes/github_dark_high_contrast.toml",
  # "~/.config/alacritty/themes/themes/theme.toml",
  # "~/.config/alacritty/themes/themes/theme.toml",
  # "~/.config/alacritty/themes/themes/theme.toml",
  # "~/.config/alacritty/themes/themes/theme.toml",
  # "~/.config/alacritty/themes/themes/theme.toml",

  # Light Theme
  # "~/.config/alacritty/themes/themes/catppuccin_latte.toml",
  # "~/.config/alacritty/themes/themes/everforest_light.toml",
  # "~/.config/alacritty/themes/themes/ashes_light.toml", # pale
  # "~/.config/alacritty/themes/themes/atom_one_light.toml", # vivid
  # "~/.config/alacritty/themes/themes/ayu_light.toml", # I like it
  # "~/.config/alacritty/themes/themes/theme.toml",
  # "~/.config/alacritty/themes/themes/theme.toml",
  # "~/.config/alacritty/themes/themes/theme.toml",
  # "~/.config/alacritty/themes/themes/theme.toml",
  # "~/.config/alacritty/themes/themes/theme.toml",
  # "~/.config/alacritty/themes/themes/theme.toml",
  # "~/.config/alacritty/themes/themes/theme.toml",
]
