mode = "local"
project = ""
shell = ""

[dirs]
project = []
python = "isolated"
data = "/home/aster/.local/share/hatch"
cache = "/home/aster/.cache/hatch"

[dirs.env]
virtual = ".venv"

[projects]

[publish.index]
repo = "main"

[template]
name = "aster"
email = "137767097+aster-void@users.noreply.github.com"

[template.licenses]
headers = true
default = ["MIT"]

[template.plugins.default]
tests = true
ci = false
src-layout = true

[terminal.styles]
info = "bold"
success = "bold cyan"
error = "bold red"
warning = "bold yellow"
waiting = "bold magenta"
debug = "bold"
spinner = "simpleDotsScrolling"
