theme = "catppuccin_macchiato"
# catppuccin_{frappe, macchiato} onedark, 

[editor]
line-number = "relative"
middle-click-paste = false

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.file-picker]
hidden = false
