theme = "catppuccin_frappe"
# Dark:
# catppuccin_{frappe, macchiato} onedark, 
# Light:
# catppuccin_latte

[editor]
line-number = "relative"
middle-click-paste = false

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.file-picker]
hidden = false
