theme = "catppuccin_frappe"
# Dark:
# - catppuccin_{frappe, macchiato}
# - onedark
# - dark_plus,
# - everforest_dark, 
# Light:
# - bogster_light 
#   vivid:
#   - papercolor-light 
#   - onelight
#   - zed_onelight
#   - catppuccin_latte
# Transparent:
# - base16_transparent

[editor]
line-number = "relative"
middle-click-paste = false
idle-timeout = 10

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true
