[language-server]
biome = { command = "biome", args = ["lsp-proxy"] }

[[language]]
name = "nix"
auto-format = true
formatter.command = "nixpkgs-fmt"
language-servers = ["nixd"]

[language-server.nixd]
command = "nixd"

[[language]]
name = "rust"
auto-format = true
language-servers = ["rust-analyzer"]

[[language]]
name = "clangd"
auto-format = true
scope = ".c"
file-types = ["C"]

[[language]]
name = "fsharp"
auto-format = true

# [language.config.inlayHints]
# bindingModeHints.enable = true
# chainingHints.enable = true
# closingBraceHints.enable = true
# closingBraceHints.minLines = 1
# closureCaptureHints.enable = true
# closureReturnTypeHints.enable = "always"
# expressionAdjustmentHints.enable = true
# rangeExclusiveHints.enable = true

[[language]]
name = "toml"
auto-format = true
formatter.command = "taplo"
formatter.args = ["fmt", "-"]


[[langugage]]
name = "go"
auto-format = true

[[langugage]]
name = "gleam"
auto-format = true


[[language]]
name = "markdown"
auto-format = true

[[language]]
name = "mdx"
file-types = ["mdx"]
scope = ".mdx"
language-servers = ["markdown-oxide"]


[[language]]
name = "html"
language-servers = ["vscode-html-language-server", "tailwindcss-ls"]

[[language]]
name = "css"
language-servers = ["vscode-css-language-server", "tailwindcss-ls"]

[[language]]
name = "typescript"
auto-format = true
language-servers = [
  "biome",
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
]

[[language]]
name = "tsx"
auto-format = true
language-servers = [
  "biome",
  "tailwindcss-ls",
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
]
