
[[language]]
name = "nix"
auto-format = true
formatter.command = "nixpkgs-fmt"
language-servers = ["nixd"]

[language-server.nixd]
command = "nixd"

[[language]]
name = "rust"
auto-format = true
language-servers = ["rust-analyzer"]

[[language]]
name = "clangd"
auto-format = true
scope = ".c"
file-types = ["C"]

# [language.config.inlayHints]
# bindingModeHints.enable = true
# chainingHints.enable = true
# closingBraceHints.enable = true
# closingBraceHints.minLines = 1
# closureCaptureHints.enable = true
# closureReturnTypeHints.enable = "always"
# expressionAdjustmentHints.enable = true
# rangeExclusiveHints.enable = true

[[language]]
name = "toml"
formatter.command = "taplo"
formatter.args = ["fmt", "-"]


[[langugage]]
name = "go"
auto-format = true

[[langugage]]
name = "gleam"
auto-format = true


[[language]]
name = "markdown"
auto-format = true

[[language]]
name = "mdx"
file-types = ["mdx"]
scope = ".mdx"
language-servers = ["markdown-oxide"]


[[language]]
name = "html"
language-servers = ["vscode-html-language-server", "tailwindcss-ls"]

[[language]]
name = "css"
language-servers = ["vscode-css-language-server", "tailwindcss-ls"]

[[language]]
name = "javascript"
auto-format = true

[[language]]
name = "jsx"
auto-format = true
language-servers = ["typescript-language-server"]
